pipeline:
  build_image:
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+drone
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/openjdk11
    secrets: [ DOCKER_PASSWORD ]
    tags:
      - ${DRONE_COMMIT_SHA}
    when:
      event: push

  build_image_tag:
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+drone
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/openjdk11
    secrets: [ DOCKER_PASSWORD ]
    tags:
      - ${DRONE_TAG}
      - latest
    when:
      event: tag

  scan:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    environment:
      - WHITELIST=CVE-2019-5827
    image_name: quay.io/ukhomeofficedigital/openjdk11:${DRONE_COMMIT_SHA}
    local_image: true
    when:
      event: push